### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by sampsonye** [bytebeats/commits-changelog-env-plugin#1]
![image](https://user-images.githubusercontent.com/5895634/175197975-861c7eca-76ca-4df4-8c49-474cd550fabd.png)

**Comment by sampsonye** [comment]
![image](https://user-images.githubusercontent.com/5895634/175204392-a0d84fd1-b406-4f39-87b8-e0c6acf15fdc.png)

**Comment by bytebeats** [comment]
@sampsonye change file encodings from ISO to UTF-8.

**Comment by bytebeats** [comment]
@sampsonye `Intellij IDEA` -> `Preferences` -> `Editor` -> `File Encodings` -> `Properties File(*.properties)`, select `UTF-8`.

**Comment by sampsonye** [comment]
使用你的hpi包也是乱码呀 @bytebeats 这个怎么处理呢
另我在idea中修改编码后，编译出来的hpi包还是乱码

另我在idea中显示没有Messages这个类是什么问题
![image](https://user-images.githubusercontent.com/5895634/175245376-cd7f118f-6523-41e4-b898-684dca7dd136.png)

**Comment by bytebeats** [comment]
@sampsonye Messages is auto-generated after compiled. Run `Build` -> `Build Project`/`Rebuild project`.  Also, maybe your Jenkins configuration not support UTF-8? I really don't know.

**Comment by bytebeats** [comment]
或者就直接删除多语言然后再打包
